### ISSUE TITLE
[QUESTION] - 

### ISSUE THREAD

**Issue by sldev2021** [alefragnani/vscode-delphi-pack#7]
Hi Alessandro, really thanks for your work on this exstension!
this is my Unit1.pas content in VLC applicaztion:

procedure TForm1.Button1Click(Sender: TObject);
begin
  var a:= '';
  if a <> '' then
  begin
    a := 'create snippet';
  end;
  SayHello('Word');
  OutputDebugString('test string 2');
end;

procedure TForm1.SayHello(name: string);
begin
  ShowMessage('Hello ' + name);
end;

I've configured according to: https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal
my task.json file
In VS Code:
-> Ctrl + Shift + P
-> Task: Run Task Build

in: VS Code-Terminal got:
Embarcadero Delphi for Win32 compiler version 34.0
Copyright (c) 1983,2021 Embarcadero Technologies, Inc.
Unit1.pas(115)     
VSCodeTest.dpr(15) 
132 lines, 0.16 seconds, 2191344 bytes code, 48768 bytes data.

this correclty create my VSCodeTest.exe,
Is possible and how to launch and start debug?

Thanks, regards

**Comment by alefragnani** [comment]
Hi @sldev2021 ,

Thank you for you kind words. I’m glad to know you like the extension pack.

About debugging, I’m sorry to say, but the extension does not support. Delphi doesn’t _expose_ the debugger so, there is no way to reuse it on VS Code.

However, there is an extension that supports GDB (https://marketplace.visualstudio.com/items?itemName=webfreak.debug), and based on some its documentation and some comments in its repo, it seems to work on basic scenarios.  Maybe you could try out.

Hope this helps
