### ISSUE TITLE
Database components

### ISSUE THREAD

**Issue by mariogdias** [alefragnani/vscode-delphi-pack#9]
This plugin has the database components?

**Comment by alefragnani** [comment]
Hi @mariogdias ,

I suppose you are referring to the **Data Explorer** window, where you manages and connects to databases. If that's the case, no, this extension pack doesn't includes any.

Personally, I don't use any database related extension in VS Code, but I remember there are quite a few available. Some specifics for a single database and other more generic. But none, as far as I remember, using FireDAC library behind the scenes.

Hope this helps
